package com.example.words.api;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public class DatabaseCombinationStore {

    private final JdbcTemplate jdbcTemplate;

    public DatabaseCombinationStore(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS stored_combinations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    combination VARCHAR(2048) NOT NULL
                )
                """);
    }

    public void replace(List<String> combinations) {
        jdbcTemplate.update("DELETE FROM stored_combinations");
        jdbcTemplate.batchUpdate(
                "INSERT INTO stored_combinations (combination) VALUES (?)",
                combinations,
                combinations.size(),
                (statement, combination) -> statement.setString(1, combination));
    }

    public List<String> findAll() {
        return jdbcTemplate.query(
                "SELECT combination FROM stored_combinations ORDER BY id",
                (resultSet, rowNumber) -> resultSet.getString("combination"));
    }
}
